import { PrismaClient, Prisma } from '@prisma/client';
import bcrypt from 'bcryptjs';

const prisma = new PrismaClient();

async function main() {
  console.log('Seeding database with demo data...');

  // 1. Create Demo Organization
  const organization = await prisma.organization.upsert({
    where: { slug: 'demo-agency' },
    update: {},
    create: {
      name: 'Wealth Pro Agency',
      slug: 'demo-agency',
      primaryColor: '#3B82F6',
      secondaryColor: '#1E40AF',
      plan: 'PROFESSIONAL',
      maxAgents: 10,
      maxContacts: 2000,
      smsEnabled: true,
      eSignEnabled: true,
    },
  });
  console.log('Created organization:', organization.name);

  // 2. Create Demo Agent
  const passwordHash = await bcrypt.hash('demo1234', 10);
  const agent = await prisma.agent.upsert({
    where: { email: 'demo@wealthpro.com' },
    update: {},
    create: {
      email: 'demo@wealthpro.com',
      passwordHash,
      firstName: 'Michael',
      lastName: 'Anderson',
      phone: '(808) 555-1234',
      role: 'MANAGER',
      referralCode: 'DEMO2024',
      organizationId: organization.id,
      licenseNumber: 'LIC-2024-001',
      licenseDate: new Date('2020-03-15'),
      monthlyGoal: new Prisma.Decimal(15000),
    },
  });
  console.log('Created demo agent:', agent.email);

  // 3. Create Demo Prospects with Financial Profiles
  const prospectsData = [
    {
      email: 'john.smith@email.com',
      firstName: 'John',
      lastName: 'Smith',
      phone: '(808) 555-2001',
      status: 'INSURANCE_CLIENT' as const,
      stage: 'CLOSED_WON' as const,
      profile: {
        annualIncome: 145000,
        spouseIncome: 65000,
        otherIncome: 5000,
        monthlyExpenses: 8500,
        housingCost: 3200,
        debtPayments: 1500,
        utilities: 350,
        food: 1200,
        transportation: 800,
        insurance: 450,
        childcare: 0,
        entertainment: 500,
        otherExpenses: 500,
        savings: 45000,
        emergencyFund: 25000,
        investments: 120000,
        retirement401k: 280000,
        rothIra: 45000,
        pensionValue: 0,
        hsaFsa: 8500,
        homeMarketValue: 750000,
        homeEquity: 280000,
        investmentProperty: 0,
        businessEquity: 0,
        otherAssets: 15000,
        mortgage: 470000,
        carLoans: 28000,
        studentLoans: 0,
        creditCards: 4500,
        personalLoans: 0,
        otherDebts: 0,
        age: 42,
        spouseAge: 40,
        dependents: 2,
        retirementAge: 62,
        occupation: 'Software Engineer',
        spouseOccupation: 'Marketing Manager',
        stateOfResidence: 'Hawaii',
        currentLifeInsurance: 250000,
        spouseLifeInsurance: 100000,
        currentDisability: 5000,
        hospitalDailyBenefit: 0,
        liabilityInsurance: 0,
        hasWill: true,
        hasTrust: false,
        netWorth: 816000,
        monthlyGap: 0,
        protectionGap: 1850000,
        personalProperty: 35000,
        taxesOwed: 0,
        businessDebt: 0,
      },
    },
    {
      email: 'sarah.chen@email.com',
      firstName: 'Sarah',
      lastName: 'Chen',
      phone: '(808) 555-2002',
      status: 'QUALIFIED' as const,
      stage: 'PROPOSAL_SENT' as const,
      profile: {
        annualIncome: 185000,
        spouseIncome: 0,
        otherIncome: 12000,
        monthlyExpenses: 7200,
        housingCost: 2800,
        debtPayments: 800,
        utilities: 280,
        food: 800,
        transportation: 600,
        insurance: 320,
        childcare: 1200,
        entertainment: 400,
        otherExpenses: 0,
        savings: 78000,
        emergencyFund: 35000,
        investments: 95000,
        retirement401k: 420000,
        rothIra: 68000,
        pensionValue: 0,
        hsaFsa: 12000,
        homeMarketValue: 920000,
        homeEquity: 420000,
        investmentProperty: 285000,
        businessEquity: 150000,
        otherAssets: 25000,
        mortgage: 500000,
        carLoans: 15000,
        studentLoans: 45000,
        creditCards: 2200,
        personalLoans: 0,
        otherDebts: 0,
        age: 38,
        spouseAge: null,
        dependents: 1,
        retirementAge: 58,
        occupation: 'Physician',
        spouseOccupation: null,
        stateOfResidence: 'Hawaii',
        currentLifeInsurance: 500000,
        spouseLifeInsurance: 0,
        currentDisability: 8000,
        hospitalDailyBenefit: 200,
        liabilityInsurance: 1000000,
        hasWill: true,
        hasTrust: true,
        netWorth: 1525800,
        monthlyGap: 0,
        protectionGap: 1470000,
        personalProperty: 45000,
        taxesOwed: 8500,
        businessDebt: 0,
      },
    },
    {
      email: 'david.martinez@email.com',
      firstName: 'David',
      lastName: 'Martinez',
      phone: '(808) 555-2003',
      status: 'AGENT_PROSPECT' as const,
      stage: 'MEETING_SCHEDULED' as const,
      profile: {
        annualIncome: 95000,
        spouseIncome: 72000,
        otherIncome: 0,
        monthlyExpenses: 6800,
        housingCost: 2400,
        debtPayments: 1200,
        utilities: 320,
        food: 950,
        transportation: 700,
        insurance: 380,
        childcare: 450,
        entertainment: 400,
        otherExpenses: 0,
        savings: 28000,
        emergencyFund: 15000,
        investments: 45000,
        retirement401k: 135000,
        rothIra: 22000,
        pensionValue: 0,
        hsaFsa: 4500,
        homeMarketValue: 580000,
        homeEquity: 145000,
        investmentProperty: 0,
        businessEquity: 0,
        otherAssets: 8000,
        mortgage: 435000,
        carLoans: 32000,
        studentLoans: 28000,
        creditCards: 8500,
        personalLoans: 5000,
        otherDebts: 0,
        age: 35,
        spouseAge: 33,
        dependents: 3,
        retirementAge: 65,
        occupation: 'Sales Manager',
        spouseOccupation: 'Teacher',
        stateOfResidence: 'Hawaii',
        currentLifeInsurance: 150000,
        spouseLifeInsurance: 50000,
        currentDisability: 0,
        hospitalDailyBenefit: 0,
        liabilityInsurance: 0,
        hasWill: false,
        hasTrust: false,
        netWorth: -105000,
        monthlyGap: 0,
        protectionGap: 1470000,
        personalProperty: 22000,
        taxesOwed: 0,
        businessDebt: 0,
      },
      agentProjection: {
        hoursPerWeek: 20,
        networkSize: 150,
        yearlyProjections: [
          { year: 1, income: 48000, clients: 24, recruits: 2 },
          { year: 2, income: 72000, clients: 36, recruits: 4 },
          { year: 3, income: 108000, clients: 54, recruits: 6 },
          { year: 4, income: 156000, clients: 72, recruits: 8 },
          { year: 5, income: 210000, clients: 96, recruits: 10 },
        ],
        year1Income: 48000,
        year3Income: 108000,
        year5Income: 210000,
        lifetimeValue: 2500000,
      },
    },
    {
      email: 'emily.wong@email.com',
      firstName: 'Emily',
      lastName: 'Wong',
      phone: '(808) 555-2004',
      status: 'LEAD' as const,
      stage: 'NEW' as const,
      profile: {
        annualIncome: 125000,
        spouseIncome: 85000,
        otherIncome: 8000,
        monthlyExpenses: 9200,
        housingCost: 3500,
        debtPayments: 1800,
        utilities: 400,
        food: 1100,
        transportation: 900,
        insurance: 500,
        childcare: 600,
        entertainment: 400,
        otherExpenses: 0,
        savings: 52000,
        emergencyFund: 18000,
        investments: 78000,
        retirement401k: 195000,
        rothIra: 35000,
        pensionValue: 25000,
        hsaFsa: 6500,
        homeMarketValue: 680000,
        homeEquity: 185000,
        investmentProperty: 0,
        businessEquity: 0,
        otherAssets: 12000,
        mortgage: 495000,
        carLoans: 45000,
        studentLoans: 65000,
        creditCards: 12000,
        personalLoans: 8000,
        otherDebts: 0,
        age: 34,
        spouseAge: 32,
        dependents: 2,
        retirementAge: 60,
        occupation: 'Project Manager',
        spouseOccupation: 'Accountant',
        stateOfResidence: 'Hawaii',
        currentLifeInsurance: 100000,
        spouseLifeInsurance: 50000,
        currentDisability: 3000,
        hospitalDailyBenefit: 0,
        liabilityInsurance: 0,
        hasWill: false,
        hasTrust: false,
        netWorth: -18500,
        monthlyGap: 0,
        protectionGap: 2030000,
        personalProperty: 28000,
        taxesOwed: 3500,
        businessDebt: 0,
      },
    },
    {
      email: 'robert.kim@email.com',
      firstName: 'Robert',
      lastName: 'Kim',
      phone: '(808) 555-2005',
      status: 'QUALIFIED' as const,
      stage: 'NEEDS_ANALYSIS' as const,
      profile: {
        annualIncome: 220000,
        spouseIncome: 0,
        otherIncome: 35000,
        monthlyExpenses: 12500,
        housingCost: 4800,
        debtPayments: 2500,
        utilities: 550,
        food: 1500,
        transportation: 1200,
        insurance: 650,
        childcare: 0,
        entertainment: 800,
        otherExpenses: 500,
        savings: 125000,
        emergencyFund: 65000,
        investments: 380000,
        retirement401k: 680000,
        rothIra: 95000,
        pensionValue: 0,
        hsaFsa: 18000,
        homeMarketValue: 1450000,
        homeEquity: 650000,
        investmentProperty: 520000,
        businessEquity: 280000,
        otherAssets: 45000,
        mortgage: 800000,
        carLoans: 55000,
        studentLoans: 0,
        creditCards: 8000,
        personalLoans: 0,
        otherDebts: 0,
        age: 52,
        spouseAge: null,
        dependents: 0,
        retirementAge: 60,
        occupation: 'Business Owner',
        spouseOccupation: null,
        stateOfResidence: 'Hawaii',
        currentLifeInsurance: 750000,
        spouseLifeInsurance: 0,
        currentDisability: 12000,
        hospitalDailyBenefit: 300,
        liabilityInsurance: 2000000,
        hasWill: true,
        hasTrust: true,
        netWorth: 1995000,
        monthlyGap: 0,
        protectionGap: 1800000,
        personalProperty: 85000,
        taxesOwed: 22000,
        businessDebt: 45000,
      },
    },
    {
      email: 'jennifer.lee@email.com',
      firstName: 'Jennifer',
      lastName: 'Lee',
      phone: '(808) 555-2006',
      status: 'LEAD' as const,
      stage: 'CONTACTED' as const,
      profile: {
        annualIncome: 78000,
        spouseIncome: 62000,
        otherIncome: 0,
        monthlyExpenses: 5800,
        housingCost: 2200,
        debtPayments: 900,
        utilities: 280,
        food: 800,
        transportation: 550,
        insurance: 320,
        childcare: 350,
        entertainment: 300,
        otherExpenses: 100,
        savings: 18000,
        emergencyFund: 8000,
        investments: 25000,
        retirement401k: 85000,
        rothIra: 15000,
        pensionValue: 0,
        hsaFsa: 3200,
        homeMarketValue: 485000,
        homeEquity: 95000,
        investmentProperty: 0,
        businessEquity: 0,
        otherAssets: 5000,
        mortgage: 390000,
        carLoans: 22000,
        studentLoans: 35000,
        creditCards: 6500,
        personalLoans: 0,
        otherDebts: 0,
        age: 29,
        spouseAge: 28,
        dependents: 1,
        retirementAge: 65,
        occupation: 'Marketing Specialist',
        spouseOccupation: 'Nurse',
        stateOfResidence: 'Hawaii',
        currentLifeInsurance: 50000,
        spouseLifeInsurance: 25000,
        currentDisability: 0,
        hospitalDailyBenefit: 0,
        liabilityInsurance: 0,
        hasWill: false,
        hasTrust: false,
        netWorth: -189300,
        monthlyGap: 0,
        protectionGap: 1325000,
        personalProperty: 15000,
        taxesOwed: 0,
        businessDebt: 0,
      },
    },
    {
      email: 'michael.tanaka@email.com',
      firstName: 'Michael',
      lastName: 'Tanaka',
      phone: '(808) 555-2007',
      status: 'INSURANCE_CLIENT' as const,
      stage: 'CLOSED_WON' as const,
      profile: {
        annualIncome: 165000,
        spouseIncome: 95000,
        otherIncome: 15000,
        monthlyExpenses: 11000,
        housingCost: 4200,
        debtPayments: 1800,
        utilities: 420,
        food: 1300,
        transportation: 1000,
        insurance: 580,
        childcare: 1200,
        entertainment: 500,
        otherExpenses: 0,
        savings: 85000,
        emergencyFund: 42000,
        investments: 165000,
        retirement401k: 385000,
        rothIra: 72000,
        pensionValue: 45000,
        hsaFsa: 14000,
        homeMarketValue: 890000,
        homeEquity: 345000,
        investmentProperty: 0,
        businessEquity: 0,
        otherAssets: 22000,
        mortgage: 545000,
        carLoans: 38000,
        studentLoans: 15000,
        creditCards: 5500,
        personalLoans: 0,
        otherDebts: 0,
        age: 45,
        spouseAge: 43,
        dependents: 2,
        retirementAge: 62,
        occupation: 'Financial Analyst',
        spouseOccupation: 'HR Director',
        stateOfResidence: 'Hawaii',
        currentLifeInsurance: 500000,
        spouseLifeInsurance: 250000,
        currentDisability: 8500,
        hospitalDailyBenefit: 150,
        liabilityInsurance: 1000000,
        hasWill: true,
        hasTrust: true,
        netWorth: 1026500,
        monthlyGap: 0,
        protectionGap: 2000000,
        personalProperty: 42000,
        taxesOwed: 5200,
        businessDebt: 0,
      },
    },
    {
      email: 'amanda.patel@email.com',
      firstName: 'Amanda',
      lastName: 'Patel',
      phone: '(808) 555-2008',
      status: 'AGENT_PROSPECT' as const,
      stage: 'NEGOTIATION' as const,
      profile: {
        annualIncome: 88000,
        spouseIncome: 0,
        otherIncome: 6000,
        monthlyExpenses: 4500,
        housingCost: 1800,
        debtPayments: 600,
        utilities: 220,
        food: 650,
        transportation: 450,
        insurance: 280,
        childcare: 0,
        entertainment: 350,
        otherExpenses: 150,
        savings: 32000,
        emergencyFund: 15000,
        investments: 48000,
        retirement401k: 125000,
        rothIra: 28000,
        pensionValue: 0,
        hsaFsa: 5500,
        homeMarketValue: 0,
        homeEquity: 0,
        investmentProperty: 0,
        businessEquity: 0,
        otherAssets: 8000,
        mortgage: 0,
        carLoans: 18000,
        studentLoans: 42000,
        creditCards: 3500,
        personalLoans: 0,
        otherDebts: 0,
        age: 31,
        spouseAge: null,
        dependents: 0,
        retirementAge: 55,
        occupation: 'Software Developer',
        spouseOccupation: null,
        stateOfResidence: 'Hawaii',
        currentLifeInsurance: 100000,
        spouseLifeInsurance: 0,
        currentDisability: 4000,
        hospitalDailyBenefit: 0,
        liabilityInsurance: 0,
        hasWill: false,
        hasTrust: false,
        netWorth: 198000,
        monthlyGap: 0,
        protectionGap: 840000,
        personalProperty: 12000,
        taxesOwed: 0,
        businessDebt: 0,
      },
      agentProjection: {
        hoursPerWeek: 15,
        networkSize: 200,
        yearlyProjections: [
          { year: 1, income: 36000, clients: 18, recruits: 1 },
          { year: 2, income: 54000, clients: 27, recruits: 2 },
          { year: 3, income: 81000, clients: 40, recruits: 4 },
          { year: 4, income: 117000, clients: 55, recruits: 6 },
          { year: 5, income: 162000, clients: 75, recruits: 8 },
        ],
        year1Income: 36000,
        year3Income: 81000,
        year5Income: 162000,
        lifetimeValue: 1800000,
      },
    },
  ];

  for (const prospectData of prospectsData) {
    const prospect = await prisma.prospect.upsert({
      where: { email: prospectData.email },
      update: {},
      create: {
        email: prospectData.email,
        firstName: prospectData.firstName,
        lastName: prospectData.lastName,
        phone: prospectData.phone,
        status: prospectData.status,
        stage: prospectData.stage,
        agentId: agent.id,
        referredByAgentId: agent.id,
        referralSource: 'balance-sheet-DEMO2024',
      },
    });

    // Create financial profile
    await prisma.financialProfile.upsert({
      where: { prospectId: prospect.id },
      update: {},
      create: {
        prospectId: prospect.id,
        ...prospectData.profile,
      },
    });

    // Create agent projection if exists
    if ('agentProjection' in prospectData && prospectData.agentProjection) {
      await prisma.agentProjection.upsert({
        where: { prospectId: prospect.id },
        update: {},
        create: {
          prospectId: prospect.id,
          hoursPerWeek: prospectData.agentProjection.hoursPerWeek,
          networkSize: prospectData.agentProjection.networkSize,
          yearlyProjections: prospectData.agentProjection.yearlyProjections,
          year1Income: prospectData.agentProjection.year1Income,
          year3Income: prospectData.agentProjection.year3Income,
          year5Income: prospectData.agentProjection.year5Income,
          lifetimeValue: prospectData.agentProjection.lifetimeValue,
        },
      });
    }

    console.log('Created prospect:', prospectData.firstName, prospectData.lastName);
  }

  // 4. Create Activities
  const activities = [
    { type: 'PRESENTATION' as const, title: 'Financial Review Presentation', description: 'Completed comprehensive financial review with John Smith', prospectEmail: 'john.smith@email.com', daysAgo: 2 },
    { type: 'CALL' as const, title: 'Follow-up Call', description: 'Discussed term life options with Sarah Chen', prospectEmail: 'sarah.chen@email.com', daysAgo: 1 },
    { type: 'MEETING' as const, title: 'Career Opportunity Meeting', description: 'Presented agent career path to David Martinez', prospectEmail: 'david.martinez@email.com', daysAgo: 0 },
    { type: 'EMAIL' as const, title: 'Proposal Sent', description: 'Sent insurance proposal to Sarah Chen', prospectEmail: 'sarah.chen@email.com', daysAgo: 3 },
    { type: 'OTHER' as const, title: 'New Balance Sheet Submission', description: 'Emily Wong completed their Living Balance Sheet via your personal link.', prospectEmail: 'emily.wong@email.com', daysAgo: 0 },
    { type: 'FOLLOW_UP' as const, title: 'Scheduled Follow-up', description: 'Set reminder to follow up with Robert Kim about business coverage', prospectEmail: 'robert.kim@email.com', daysAgo: 1 },
  ];

  for (const activity of activities) {
    const prospect = await prisma.prospect.findUnique({ where: { email: activity.prospectEmail } });
    if (prospect) {
      await prisma.activity.create({
        data: {
          agentId: agent.id,
          prospectId: prospect.id,
          type: activity.type,
          title: activity.title,
          description: activity.description,
          createdAt: new Date(Date.now() - activity.daysAgo * 24 * 60 * 60 * 1000),
        },
      });
    }
  }
  console.log('Created activities');

  // 5. Create Business Prospects
  const businessProspectsData = [
    {
      email: 'owner@hawaiiangrillco.com',
      firstName: 'James',
      lastName: 'Nakamura',
      phone: '(808) 555-3001',
      businessName: 'Hawaiian Grill Co.',
      businessType: 'LLC' as const,
      industry: 'Restaurant',
      yearsInBusiness: 8,
      employeeCount: 15,
      status: 'QUALIFIED' as const,
      profile: {
        annualRevenue: 1850000,
        costOfGoodsSold: 648000,
        grossProfit: 1202000,
        netIncome: 185000,
        ownerSalary: 120000,
        ownerDistributions: 45000,
        cashOnHand: 85000,
        accountsReceivable: 12000,
        inventory: 35000,
        prepaidExpenses: 8000,
        equipment: 125000,
        vehicles: 45000,
        realEstate: 0,
        leaseholdImprovements: 95000,
        intellectualProperty: 15000,
        goodwill: 50000,
        investments: 25000,
        otherAssets: 10000,
        accountsPayable: 28000,
        accruedExpenses: 15000,
        shortTermLoans: 25000,
        creditCards: 8000,
        lineOfCredit: 35000,
        currentPortionLTD: 24000,
        termLoans: 85000,
        sbaLoans: 120000,
        equipmentLoans: 35000,
        commercialMortgage: 0,
        otherLongTermDebt: 0,
        keyPersonInsurance: 250000,
        generalLiability: 1000000,
        professionalLiability: 0,
        propertyInsurance: 500000,
        workersComp: 150000,
        businessInterruption: 0,
        cyberLiability: 0,
        buyerSellerAgreement: false,
        successionPlan: false,
        totalAssets: 505000,
        totalLiabilities: 375000,
        netWorth: 130000,
        currentRatio: 1.27,
        debtToEquityRatio: 2.88,
        keyPersonGap: 3450000,
        buyoutFundingGap: 130000,
      },
    },
    {
      email: 'ceo@pacifictech.io',
      firstName: 'Michelle',
      lastName: 'Watanabe',
      phone: '(808) 555-3002',
      businessName: 'Pacific Tech Solutions',
      businessType: 'S_CORP' as const,
      industry: 'Technology Services',
      yearsInBusiness: 5,
      employeeCount: 8,
      status: 'LEAD' as const,
      profile: {
        annualRevenue: 920000,
        costOfGoodsSold: 184000,
        grossProfit: 736000,
        netIncome: 165000,
        ownerSalary: 150000,
        ownerDistributions: 35000,
        cashOnHand: 145000,
        accountsReceivable: 85000,
        inventory: 0,
        prepaidExpenses: 12000,
        equipment: 65000,
        vehicles: 28000,
        realEstate: 0,
        leaseholdImprovements: 25000,
        intellectualProperty: 75000,
        goodwill: 0,
        investments: 85000,
        otherAssets: 5000,
        accountsPayable: 18000,
        accruedExpenses: 22000,
        shortTermLoans: 0,
        creditCards: 5000,
        lineOfCredit: 25000,
        currentPortionLTD: 12000,
        termLoans: 45000,
        sbaLoans: 0,
        equipmentLoans: 18000,
        commercialMortgage: 0,
        otherLongTermDebt: 0,
        keyPersonInsurance: 500000,
        generalLiability: 1000000,
        professionalLiability: 2000000,
        propertyInsurance: 250000,
        workersComp: 50000,
        businessInterruption: 100000,
        cyberLiability: 500000,
        buyerSellerAgreement: true,
        successionPlan: false,
        totalAssets: 525000,
        totalLiabilities: 145000,
        netWorth: 380000,
        currentRatio: 3.88,
        debtToEquityRatio: 0.38,
        keyPersonGap: 1340000,
        buyoutFundingGap: 0,
      },
    },
  ];

  for (const bpData of businessProspectsData) {
    const businessProspect = await prisma.businessProspect.upsert({
      where: { email: bpData.email },
      update: {},
      create: {
        email: bpData.email,
        firstName: bpData.firstName,
        lastName: bpData.lastName,
        phone: bpData.phone,
        businessName: bpData.businessName,
        businessType: bpData.businessType,
        industry: bpData.industry,
        yearsInBusiness: bpData.yearsInBusiness,
        employeeCount: bpData.employeeCount,
        status: bpData.status,
        agentId: agent.id,
        referredByAgentId: agent.id,
      },
    });

    await prisma.businessFinancialProfile.upsert({
      where: { businessProspectId: businessProspect.id },
      update: {},
      create: {
        businessProspectId: businessProspect.id,
        ...bpData.profile,
      },
    });

    console.log('Created business prospect:', bpData.businessName);
  }

  console.log('\n========================================');
  console.log('Demo data seeded successfully!');
  console.log('========================================');
  console.log('Login credentials:');
  console.log('  Email: demo@wealthpro.com');
  console.log('  Password: demo1234');
  console.log('  Balance Sheet Link: /b/DEMO2024');
  console.log('========================================\n');
}

main()
  .catch((e) => {
    console.error('Seed error:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
