import jsPDF from 'jspdf';
import 'jspdf-autotable';
import type { CommissionTier } from '../config/commission.config';
import { agentConfig } from '../config/agent.config';

// Extend jsPDF type for autoTable
declare module 'jspdf' {
  interface jsPDF {
    autoTable: (options: any) => jsPDF;
  }
}

interface ProjectionData {
  year: number;
  newCommission: number;
  renewalIncome: number;
  bonus: number;
  teamOverride: number;
  total: number;
}

interface PDFExportParams {
  monthlyPolicies: number;
  avgPremium: number;
  renewalBook: number;
  currentTier: CommissionTier;
  projections: ProjectionData[];
  totalFirstYearIncome: number;
  teamOverrideIncome: number;
  teamProduction: number;
  teamOverridePercentage: number;
}

const formatCurrency = (amount: number): string => {
  return new Intl.NumberFormat('en-US', {
    style: 'currency',
    currency: 'USD',
    minimumFractionDigits: 0,
    maximumFractionDigits: 0,
  }).format(amount);
};

export function generateProjectionPDF(params: PDFExportParams): void {
  const {
    monthlyPolicies,
    avgPremium,
    renewalBook,
    currentTier,
    projections,
    totalFirstYearIncome,
    teamOverrideIncome,
    teamProduction,
    teamOverridePercentage,
  } = params;

  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  let yPos = 20;

  // Header
  doc.setFontSize(24);
  doc.setTextColor(30, 64, 175); // Blue
  doc.text('Income Potential Projection', margin, yPos);
  yPos += 10;

  doc.setFontSize(12);
  doc.setTextColor(100);
  doc.text(`Generated by ${agentConfig.platformName}`, margin, yPos);
  yPos += 5;
  doc.text(`Date: ${new Date().toLocaleDateString()}`, margin, yPos);
  yPos += 15;

  // Divider
  doc.setDrawColor(200);
  doc.line(margin, yPos, pageWidth - margin, yPos);
  yPos += 10;

  // Input Parameters Section
  doc.setFontSize(14);
  doc.setTextColor(30, 64, 175);
  doc.text('Your Assumptions', margin, yPos);
  yPos += 8;

  doc.setFontSize(11);
  doc.setTextColor(60);
  const assumptions = [
    `Monthly Policies: ${monthlyPolicies}`,
    `Average Premium: ${formatCurrency(avgPremium)}`,
    `Existing Renewal Book: ${formatCurrency(renewalBook)}`,
    `Commission Tier: ${currentTier.name} (${currentTier.lifeRate}% FYC)`,
  ];

  if (teamProduction > 0) {
    assumptions.push(`Team Production: ${formatCurrency(teamProduction)}`);
    assumptions.push(`Team Override: ${teamOverridePercentage}%`);
  }

  assumptions.forEach(text => {
    doc.text(`• ${text}`, margin + 5, yPos);
    yPos += 6;
  });
  yPos += 10;

  // First Year Summary
  doc.setFontSize(14);
  doc.setTextColor(30, 64, 175);
  doc.text('First Year Income Summary', margin, yPos);
  yPos += 10;

  const annualProduction = monthlyPolicies * avgPremium * 12;
  const firstYearCommission = (annualProduction * currentTier.lifeRate) / 100;
  const renewalIncome = (renewalBook * currentTier.renewalRate) / 100;
  const productionBonus = annualProduction >= 100000
    ? Math.floor(annualProduction / 100000) * 5000 * currentTier.bonusMultiplier
    : 0;

  doc.autoTable({
    startY: yPos,
    head: [['Income Source', 'Amount']],
    body: [
      ['New Business Commissions', formatCurrency(firstYearCommission)],
      ['Renewal Income', formatCurrency(renewalIncome)],
      ['Production Bonuses', formatCurrency(productionBonus)],
      ...(teamOverrideIncome > 0 ? [['Team Override', formatCurrency(teamOverrideIncome)]] : []),
      ['TOTAL FIRST YEAR', formatCurrency(totalFirstYearIncome)],
    ],
    theme: 'striped',
    headStyles: { fillColor: [30, 64, 175] },
    footStyles: { fillColor: [22, 163, 74], fontStyle: 'bold' },
    margin: { left: margin, right: margin },
  });

  yPos = (doc as any).lastAutoTable.finalY + 15;

  // 5-Year Projection Table
  doc.setFontSize(14);
  doc.setTextColor(30, 64, 175);
  doc.text('5-Year Income Projection', margin, yPos);
  yPos += 10;

  const projectionRows = projections.map(p => [
    `Year ${p.year}`,
    formatCurrency(p.newCommission),
    formatCurrency(p.renewalIncome),
    formatCurrency(p.bonus),
    ...(p.teamOverride > 0 ? [formatCurrency(p.teamOverride)] : []),
    formatCurrency(p.total),
  ]);

  const headers = ['Year', 'New Business', 'Renewals', 'Bonuses'];
  if (projections[0]?.teamOverride > 0) {
    headers.push('Team Override');
  }
  headers.push('Total');

  doc.autoTable({
    startY: yPos,
    head: [headers],
    body: projectionRows,
    theme: 'striped',
    headStyles: { fillColor: [30, 64, 175] },
    margin: { left: margin, right: margin },
  });

  yPos = (doc as any).lastAutoTable.finalY + 15;

  // Total 5-Year Earnings
  const total5Year = projections.reduce((sum, p) => sum + p.total, 0);
  doc.setFillColor(22, 163, 74);
  doc.roundedRect(margin, yPos, pageWidth - 2 * margin, 20, 3, 3, 'F');
  doc.setTextColor(255);
  doc.setFontSize(14);
  doc.text(`Total 5-Year Earnings: ${formatCurrency(total5Year)}`, margin + 10, yPos + 13);
  yPos += 30;

  // Disclaimer
  doc.setFontSize(8);
  doc.setTextColor(100);
  const disclaimer = [
    'IMPORTANT DISCLAIMER: This projection is for illustrative purposes only and is not a guarantee of future earnings.',
    'Individual results vary significantly based on effort, skills, market conditions, and other factors.',
    'Commission structures and bonus programs are subject to change. Past performance does not guarantee future results.',
    'Consult with your recruiting manager for the most current compensation information.',
  ];

  disclaimer.forEach(line => {
    doc.text(line, margin, yPos);
    yPos += 4;
  });

  yPos += 10;

  // Footer
  doc.setFontSize(10);
  doc.setTextColor(60);
  doc.text(`Prepared by: ${agentConfig.agentName}`, margin, yPos);
  yPos += 5;
  doc.text(`Contact: ${agentConfig.agentEmail} | ${agentConfig.agentPhone}`, margin, yPos);

  // Save PDF
  const fileName = `Income_Projection_${new Date().toISOString().split('T')[0]}.pdf`;
  doc.save(fileName);
}

export function generateComparisonPDF(
  traditionalIncome: number[],
  agentIncome: number[]
): void {
  const doc = new jsPDF();
  const margin = 20;
  let yPos = 20;

  // Header
  doc.setFontSize(24);
  doc.setTextColor(30, 64, 175);
  doc.text('Career Comparison Report', margin, yPos);
  yPos += 10;

  doc.setFontSize(12);
  doc.setTextColor(100);
  doc.text(`Generated by ${agentConfig.platformName}`, margin, yPos);
  yPos += 5;
  doc.text(`Date: ${new Date().toLocaleDateString()}`, margin, yPos);
  yPos += 15;

  // Comparison Table
  doc.setFontSize(14);
  doc.setTextColor(30, 64, 175);
  doc.text('5-Year Income Comparison', margin, yPos);
  yPos += 10;

  const rows = traditionalIncome.map((tradIncome, i) => [
    `Year ${i + 1}`,
    formatCurrency(tradIncome),
    formatCurrency(agentIncome[i]),
    formatCurrency(agentIncome[i] - tradIncome),
  ]);

  doc.autoTable({
    startY: yPos,
    head: [['Year', 'Traditional Job', 'Agent Career', 'Advantage']],
    body: rows,
    theme: 'striped',
    headStyles: { fillColor: [30, 64, 175] },
    margin: { left: margin, right: margin },
  });

  yPos = (doc as any).lastAutoTable.finalY + 15;

  // Totals
  const tradTotal = traditionalIncome.reduce((a, b) => a + b, 0);
  const agentTotal = agentIncome.reduce((a, b) => a + b, 0);

  doc.autoTable({
    startY: yPos,
    body: [
      ['5-Year Total (Traditional)', formatCurrency(tradTotal)],
      ['5-Year Total (Agent)', formatCurrency(agentTotal)],
      ['Additional Earnings as Agent', formatCurrency(agentTotal - tradTotal)],
    ],
    theme: 'plain',
    styles: { fontStyle: 'bold' },
    margin: { left: margin, right: margin },
  });

  yPos = (doc as any).lastAutoTable.finalY + 20;

  // Disclaimer
  doc.setFontSize(8);
  doc.setTextColor(100);
  const disclaimer = [
    'DISCLAIMER: This comparison is for illustrative purposes only. Traditional job income assumes 4% annual raises.',
    'Agent income projections are based on consistent production and are not guaranteed.',
    'Individual results vary. Past performance does not guarantee future results.',
  ];

  disclaimer.forEach(line => {
    doc.text(line, margin, yPos);
    yPos += 4;
  });

  doc.save(`Career_Comparison_${new Date().toISOString().split('T')[0]}.pdf`);
}
